"""以下信息为系统地址"""
from selenium.webdriver.common.by import By

url = "https://litemall.hogwarts.ceshiren.com/"

"""以下信息为登录元素"""
li_username = By.CSS_SELECTOR, "[name='username']"
li_password = By.CSS_SELECTOR, "[name='password']"
li_login_btn = By.XPATH, "//*[text()='登录']/.."

"""以下信息为商品上架元素"""
li_goods_manage = By.XPATH, "//*[text()='商品管理']"
li_goods_groud = By.XPATH, "//*[text()='商品上架']"
li_goods_num = By.XPATH, "//*[contains(text(),'商品编号')]/..//input"
li_goods_name = By.XPATH, "//*[contains(text(),'商品名称')]/..//input"
li_groud_btn = By.XPATH, "//*[text()='上架']/.."

"""以下信息为搜索商品元素"""
li_goods_list = By.XPATH, "//*[text()='商品列表']"
li_input_goods_num = By.CSS_SELECTOR, "[placeholder='请输入商品编号']"
li_input_goods_name = By.CSS_SELECTOR, "[placeholder='请输入商品名称']"
li_search_btn = By.CSS_SELECTOR, ".el-icon-search"
li_broadside_btn = By.CSS_SELECTOR, ".el-table__expand-icon"

"""以下信息为添加优惠券元素"""
li_promote_manage = By.XPATH, "//*[text()='推广管理']"
li_coupon_manage = By.XPATH, "//*[text()='优惠券管理']"
li_add_coupon = By.CSS_SELECTOR, ".el-icon-edit"
li_coupon_name = By.XPATH, "//*[text()='优惠券名称']/..//input"
li_coupon_introduce = By.XPATH, "//*[text()='介绍']/..//input"
li_coupon_label = By.XPATH, "//*[text()='标签']/..//input"
li_coupon_consume = By.XPATH, "//*[text()='最低消费']/..//input"
li_coupon_full = By.XPATH, "//*[text()='满减金额']/..//input"
li_coupon_limit = By.XPATH, "//*[text()='每人限领']/..//input"
li_coupon_num = By.XPATH, "//*[text()='优惠券数量']/..//input"
li_coupon_validity = By.XPATH, "//*[text()='天']/../input"
li_coupon_sure = By.XPATH, "//*[text()='确定']"

"""以下信息为搜索优惠券元素"""
li_input_coupon_name = By.CSS_SELECTOR, "[placeholder='请输入优惠券标题']"
li_coupon_search = By.XPATH, "//*[text()='查找']"
li_coupon_detail = By.XPATH, "//*[text()='详情']"
li_search_coupon_name = By.XPATH, "//*[text()='名称']/../following-sibling::div[1]/div[1]"

"""以下信息为删除优惠券元素"""
li_delete_btn = By.XPATH, "//*[text()='删除']"

"""以下信息为对象存储元素"""
li_system_manage = By.XPATH, "//*[text()='系统管理']"
li_object_storage = By.XPATH, "//*[text()='对象存储']"
li_add_object = By.CSS_SELECTOR, ".el-icon-edit"
li_submit_file = By.CSS_SELECTOR, "[name='file']"
li_close_submit = By.XPATH, "//*[text()='上传对象']/../button"
li_input_object_name = By.CSS_SELECTOR, "[placeholder='请输入对象名称']"
li_search_object = By.CSS_SELECTOR, ".el-icon-search"
li_object_name = By.CSS_SELECTOR, ".el-table__body-wrapper tr:nth-child(1)>td:nth-child(2)"

"""以下信息为手机登录元素"""
appPackage = "com.jnzc.shipudaquan"
appActivity = "amodule.activity.main.Main"
app_myself = By.XPATH, "//*[@resource-id='com.jnzc.shipudaquan:id/nav_item5']"
app_login = By.XPATH, "//*[@text='立即登录']"
app_username = By.XPATH, "//*[@class='android.widget.EditText']"
app_next = By.XPATH, "//*[@text='下一步']"
app_passwd = By.XPATH, "//*[@text='输入密码' and @index='2']"
app_login_btn = By.XPATH, "//*[@text='登录']"

"""以下信息为查找app指定元素"""
app_VIP = By.XPATH, "//*[@resource-id='com.jnzc.shipudaquan:id/nav_item2']"
app_channel_area = By.XPATH, "//*[@class='android.support.v7.widget.RecyclerView']"
app_food_area = By.XPATH, "//*[@resource-id='com.jnzc.shipudaquan:id/rvListView']"
